// Generated by CoffeeScript 1.3.1
(function() {

  this.MathHelper = (function() {

    function MathHelper() {}

    MathHelper.generatePointsAboutCircle = function(num_points, center, radius) {
      var centered, coords, degree, degrees, step;
      step = 360 / num_points;
      degrees = [];
      degree = 0;
      while (degree < 360) {
        degrees.push(degree);
        degree += step;
      }
      coords = _.map(degrees, function(d) {
        var x, y;
        x = Math.cos(d) * radius;
        y = Math.sin(d) * radius;
        return {
          "x": x,
          "y": y
        };
      });
      centered = _.map(coords, function(c) {
        c.x += center.x;
        c.y += center.y;
        return c;
      });
      return centered;
    };

    return MathHelper;

  })();

}).call(this);
