// Generated by CoffeeScript 1.3.1
(function() {

  this.PieceManager = (function() {

    function PieceManager(board_dimensions, piece_dimensions, neighbors) {}

    PieceManager.prototype.initPieces = function(board_dimensions, piece_dimensions, neighbors) {
      var cols, piece_height, piece_width, rows, starting_id;
      starting_id = 1;
      piece_width = piece_dimensions.width;
      piece_height = piece_dimensions.height;
      rows = board_dimensions.rows;
      return cols = board_dimensions.columns;
    };

    return PieceManager;

  })();

}).call(this);
